spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/springdate?springdate=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root